services:
  # Servicio de MySQL
  mysql:
    image: mysql:8.0
    container_name: curso_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysqlutun
      MYSQL_DATABASE: Backend
      MYSQL_USER: curso_user
      MYSQL_PASSWORD: mysqlutn
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - curso_network
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-u',
          'root',
          '-proot123',
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Servicio de phpMyAdmin (interfaz web para administrar bases de datos MySQL)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: curso_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: mysqlutn
      MYSQL_ROOT_PASSWORD: mysqlutn
    ports:
      - '8080:80'
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - curso_network

volumes:
  mysql_data:
    driver: local

networks:
  curso_network:
    driver: bridge